server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: shop-picture-service-api-app
          uri: lb://SHOP-PICTURE-SERVICE-API-APP
          predicates:
            - Path=/api/v1/picture/**
        - id: shop-backed-api-app
          uri: lb://SHOP-BACKEND-API-APP
          predicates:
            - Path=/api/v1/**
        - id: shop-admin-app
          uri: lb://SHOP-ADMIN-APP
          predicates:
            - Path=/admin/**
