version: "3.9"
services:
  backend-app:
    container_name: shop-backend-api-app
    image: shop-backend-api-app:lesson_3
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/eshop"
      spring.datasource.username: postgres
      spring.datasource.password: 123
      picture.storage.path: /storage
    volumes:
          - ~/geek-eshop/storage:/storage
    networks:
      default:

  admin-app:
    container_name: shop-admin-app
    image: shop-admin-app:lesson_3
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/eshop"
      spring.datasource.username: postgres
      spring.datasource.password: 123
      picture.storage.path: /storage
    volumes:
      - ~/geek-eshop/storage:/storage
    networks:
      default:

  frontend-app:
    container_name: shop-frontend-app
    image: shop-frontend-app:lesson_3
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      default:

networks:
  default:
    external:
      name: db