version: "3.9"
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      default:

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - "6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      default:

  cloud-config-app:
    container_name: spring-cloud-config
    image: shuricans/spring-cloud-config:lesson_10
    restart: unless-stopped
    ports:
      - "8888"
    networks:
      default:

  picture-service-app:
    container_name: shop-picture-service-api-app
    image: shuricans/shop-picture-service-api-app:lesson_10
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - db
      - cloud-config-app
    environment:
      PROFILE: docker
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./storage:/storage
    networks:
      default:

  backend-app:
    container_name: shop-backend-api-app
    image: shuricans/shop-backend-api-app:lesson_10
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - db
      - cloud-config-app
      - redis
      - rabbitmq
      - shop-delivery-service
    environment:
      PROFILE: docker
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      default:

  admin-app:
    container_name: shop-admin-app
    image: shuricans/shop-admin-app:lesson_10
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - db
      - cloud-config-app
    environment:
      PROFILE: docker
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./storage:/storage
    networks:
      default:

  frontend-app:
    container_name: shop-frontend-app
    image: shuricans/shop-frontend-app:lesson_10
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
      - cloud-config-app
      - admin-app
      - backend-app
      - picture-service-app
    networks:
      default:

  shop-delivery-service:
    container_name: shop-delivery-service
    image: shuricans/shop-delivery-service:lesson_10
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - cloud-config-app
      - rabbitmq
    environment:
      PROFILE: docker
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      default:

  rabbitmq:
    container_name: rabbitmq
    image: bitnami/rabbitmq:latest
    restart: unless-stopped
    ports:
      - "5672"
      - "15672:15672"
    networks:
      default:

networks:
  default:
    external:
      name: geek-eshop