version: "3.9"
services:
  cloud-gateway:
    container_name: spring-cloud-gateway
    image: spring-cloud-gateway:lesson_8
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      eureka.client.serviceUrl.defaultZone: http://spring-eureka:8761/eureka/
    networks:
      default:

networks:
  default:
    external:
      name: db